; PlatformIO Configuration File for STM32 Robot Board (BlackPill F401CC)

[env:blackpill_f401cc]
platform = ststm32
board = blackpill_f401cc
framework = arduino
upload_protocol = dfu
build_flags = 
    -D USBCON
    -D USBD_USE_CDC
    -D HAL_PCD_MODULE_ENABLED
monitor_speed = 115200

